default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mysqltest_development

test:
  <<: *default
  database: mysqltest_test

production:
  <<: *default
  database: mysqltest_production
  username: mysqltest
  password: <%= ENV['MYSQLTEST_DATABASE_PASSWORD'] %>
